function err_str = get_vrep_error_code_string(err_code)

vrep_error_code_string = {'The function executed fine', ...
        'There is no command reply in the input buffer. This should not always be considered as an error, depending on the selected operation mode', ...
        'The function timed out (probably the network is down or too slow)', ...
        'The specified operation mode is not supported for the given function', ...
        'The function caused an error on the server side (e.g. an invalid handle was specified)', ...
        'The communication thread is still processing previous split command of the same type', ...
        'The function caused an error on the client side', ...
        'simxStart was not yet called'};
  
    if (~err_code)
        i = 1;
    else
        i = regexp(fliplr(dec2bin(err_code)),'1', 'once') + 1;
    end
    err_str = vrep_error_code_string{i};

end